"""
Generate Svelte frontend components for YARA Cryptex dictionary browser.
"""

from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
PYRO_PLATFORM_DIR = PROJECT_ROOT / "pyro-platform"


def generate_cryptex_browser_component() -> str:
    """Generate Svelte component for Cryptex dictionary browser."""
    
    code = []
    code.append("<script>")
    code.append("  import { onMount } from 'svelte';")
    code.append("  import { cryptexAPI } from '$lib/services/cryptexAPI';")
    code.append("")
    code.append("  let entries = [];")
    code.append("  let loading = true;")
    code.append("  let searchQuery = '';")
    code.append("  let selectedEntry = null;")
    code.append("  let stats = null;")
    code.append("")
    code.append("  $: filteredEntries = entries.filter(entry => {")
    code.append("    if (!searchQuery) return true;")
    code.append("    const query = searchQuery.toLowerCase();")
    code.append("    return (")
    code.append("      entry.symbol.toLowerCase().includes(query) ||")
    code.append("      entry.pyro_name.toLowerCase().includes(query) ||")
    code.append("      entry.summary.toLowerCase().includes(query)")
    code.append("    );")
    code.append("  });")
    code.append("")
    code.append("  onMount(async () => {")
    code.append("    try {")
    code.append("      entries = await cryptexAPI.getAllEntries();")
    code.append("      stats = await cryptexAPI.getStats();")
    code.append("    } catch (error) {")
    code.append("      console.error('Failed to load Cryptex dictionary:', error);")
    code.append("    } finally {")
    code.append("      loading = false;")
    code.append("    }")
    code.append("  });")
    code.append("")
    code.append("  function selectEntry(entry) {")
    code.append("    selectedEntry = entry;")
    code.append("  }")
    code.append("</script>")
    code.append("")
    code.append("<div class=\"cryptex-browser\">")
    code.append("  <div class=\"header\">")
    code.append("    <h1>YARA Cryptex Dictionary</h1>")
    code.append("    {#if stats}")
    code.append("      <div class=\"stats\">")
    code.append("        <span>{stats.total_entries} entries</span>")
    code.append("        <span>{stats.functions} functions</span>")
    code.append("        <span>{stats.cli_tools} CLI tools</span>")
    code.append("      </div>")
    code.append("    {/if}")
    code.append("  </div>")
    code.append("")
    code.append("  <div class=\"search-bar\">")
    code.append("    <input")
    code.append("      type=\"text\"")
    code.append("      placeholder=\"Search by symbol, codename, or summary...\"")
    code.append("      bind:value={searchQuery}")
    code.append("    />")
    code.append("  </div>")
    code.append("")
    code.append("  <div class=\"content\">")
    code.append("    <div class=\"entries-list\">")
    code.append("      {#if loading}")
    code.append("        <div class=\"loading\">Loading dictionary...</div>")
    code.append("      {:else if filteredEntries.length === 0}")
    code.append("        <div class=\"empty\">No entries found</div>")
    code.append("      {:else}")
    code.append("        <div class=\"entries\">")
    code.append("          {#each filteredEntries as entry (entry.symbol)}")
    code.append("            <div")
    code.append("              class=\"entry-card\"")
    code.append("              class:selected={selectedEntry?.symbol === entry.symbol}")
    code.append("              on:click={() => selectEntry(entry)}")
    code.append("            >")
    code.append("              <div class=\"entry-header\">")
    code.append("                <span class=\"symbol\">{entry.symbol}</span>")
    code.append("                <span class=\"codename\">{entry.pyro_name}</span>")
    code.append("              </div>")
    code.append("              <div class=\"entry-summary\">{entry.summary}</div>")
    code.append("              <div class=\"entry-meta\">")
    code.append("                <span class=\"kind\">{entry.kind}</span>")
    code.append("                <span class=\"location\">{entry.location}</span>")
    code.append("              </div>")
    code.append("            </div>")
    code.append("          {/each}")
    code.append("        </div>")
    code.append("      {/if}")
    code.append("    </div>")
    code.append("")
    code.append("    {#if selectedEntry}")
    code.append("      <div class=\"entry-detail\">")
    code.append("        <h2>{selectedEntry.symbol}</h2>")
    code.append("        <div class=\"detail-section\">")
    code.append("          <h3>Codename</h3>")
    code.append("          <p>{selectedEntry.pyro_name}</p>")
    code.append("        </div>")
    code.append("        <div class=\"detail-section\">")
    code.append("          <h3>Summary</h3>")
    code.append("          <p>{selectedEntry.summary}</p>")
    code.append("        </div>")
    code.append("        <div class=\"detail-section\">")
    code.append("          <h3>Signature</h3>")
    code.append("          <pre>{selectedEntry.signature}</pre>")
    code.append("        </div>")
    code.append("        <div class=\"detail-section\">")
    code.append("          <h3>Pseudocode</h3>")
    code.append("          <pre>{selectedEntry.pseudocode}</pre>")
    code.append("        </div>")
    code.append("        <div class=\"detail-section\">")
    code.append("          <h3>Location</h3>")
    code.append("          <p>{selectedEntry.location}</p>")
    code.append("        </div>")
    code.append("      </div>")
    code.append("    {/if}")
    code.append("  </div>")
    code.append("</div>")
    code.append("")
    code.append("<style>")
    code.append("  .cryptex-browser {")
    code.append("    padding: 1rem;")
    code.append("    height: 100%;")
    code.append("    display: flex;")
    code.append("    flex-direction: column;")
    code.append("  }")
    code.append("")
    code.append("  .header {")
    code.append("    margin-bottom: 1rem;")
    code.append("  }")
    code.append("")
    code.append("  .stats {")
    code.append("    display: flex;")
    code.append("    gap: 1rem;")
    code.append("    margin-top: 0.5rem;")
    code.append("  }")
    code.append("")
    code.append("  .search-bar {")
    code.append("    margin-bottom: 1rem;")
    code.append("  }")
    code.append("")
    code.append("  .search-bar input {")
    code.append("    width: 100%;")
    code.append("    padding: 0.5rem;")
    code.append("    font-size: 1rem;")
    code.append("  }")
    code.append("")
    code.append("  .content {")
    code.append("    display: grid;")
    code.append("    grid-template-columns: 1fr 1fr;")
    code.append("    gap: 1rem;")
    code.append("    flex: 1;")
    code.append("    overflow: hidden;")
    code.append("  }")
    code.append("")
    code.append("  .entries-list {")
    code.append("    overflow-y: auto;")
    code.append("  }")
    code.append("")
    code.append("  .entry-card {")
    code.append("    padding: 1rem;")
    code.append("    margin-bottom: 0.5rem;")
    code.append("    border: 1px solid #ccc;")
    code.append("    border-radius: 4px;")
    code.append("    cursor: pointer;")
    code.append("    transition: background-color 0.2s;")
    code.append("  }")
    code.append("")
    code.append("  .entry-card:hover {")
    code.append("    background-color: #f5f5f5;")
    code.append("  }")
    code.append("")
    code.append("  .entry-card.selected {")
    code.append("    background-color: #e3f2fd;")
    code.append("    border-color: #2196f3;")
    code.append("  }")
    code.append("")
    code.append("  .entry-header {")
    code.append("    display: flex;")
    code.append("    justify-content: space-between;")
    code.append("    margin-bottom: 0.5rem;")
    code.append("  }")
    code.append("")
    code.append("  .symbol {")
    code.append("    font-weight: bold;")
    code.append("    font-family: monospace;")
    code.append("  }")
    code.append("")
    code.append("  .codename {")
    code.append("    color: #666;")
    code.append("    font-size: 0.9rem;")
    code.append("  }")
    code.append("")
    code.append("  .entry-summary {")
    code.append("    margin-bottom: 0.5rem;")
    code.append("    color: #333;")
    code.append("  }")
    code.append("")
    code.append("  .entry-meta {")
    code.append("    display: flex;")
    code.append("    gap: 1rem;")
    code.append("    font-size: 0.8rem;")
    code.append("    color: #999;")
    code.append("  }")
    code.append("")
    code.append("  .entry-detail {")
    code.append("    padding: 1rem;")
    code.append("    border: 1px solid #ccc;")
    code.append("    border-radius: 4px;")
    code.append("    overflow-y: auto;")
    code.append("  }")
    code.append("")
    code.append("  .detail-section {")
    code.append("    margin-bottom: 1.5rem;")
    code.append("  }")
    code.append("")
    code.append("  .detail-section h3 {")
    code.append("    margin-bottom: 0.5rem;")
    code.append("    color: #2196f3;")
    code.append("  }")
    code.append("")
    code.append("  .detail-section pre {")
    code.append("    background: #f5f5f5;")
    code.append("    padding: 0.5rem;")
    code.append("    border-radius: 4px;")
    code.append("    overflow-x: auto;")
    code.append("  }")
    code.append("")
    code.append("  .loading, .empty {")
    code.append("    text-align: center;")
    code.append("    padding: 2rem;")
    code.append("    color: #999;")
    code.append("  }")
    code.append("</style>")
    
    return "\n".join(code)


def export_frontend_component(output_dir: Path = None):
    """Export frontend component to PYRO Platform."""
    if output_dir is None:
        output_dir = PYRO_PLATFORM_DIR / "frontend-svelte" / "src" / "routes" / "tools" / "yara" / "cryptex"
    
    output_dir.mkdir(parents=True, exist_ok=True)
    
    component = generate_cryptex_browser_component()
    component_file = output_dir / "+page.svelte"
    component_file.write_text(component, encoding='utf-8')
    
    return component_file


if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="Generate Cryptex frontend component")
    parser.add_argument("--export", action="store_true", help="Export to PYRO Platform")
    parser.add_argument("--output", type=str, help="Output directory")
    
    args = parser.parse_args()
    
    if args.export:
        output_dir = Path(args.output) if args.output else None
        component_file = export_frontend_component(output_dir)
        print("=" * 60)
        print("Frontend Component Generated:")
        print(f"  [OK] {component_file}")
        print("=" * 60)
    else:
        print(generate_cryptex_browser_component())

